# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ram's Personal Website
email: FirstName@LastName.com
description: >- # this means to ignore newlines until "baseurl:"
    Built by Ram Vasuthevan with ❤️ on the [shoulders of giants](/acknowledgements.html)
locale: en-CA 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ramvasuthevan.ca" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RamVasuthevan
github_username:  RamVasuthevan
linkedin_username: RamVasuthevan
flickr_username: RamVasuthevan


# jekyll-seo-tag based on https://github.com/jekyll/jekyll-seo-tag/blob/db0e6392591a13e33339ee250a2861fc01646146/docs/usage.md

twitter:
  username: RamVasuthevan
  card: summary_large_image

social:
  name: Ram Vasuthevan
  links:
    - https://twitter.com/RamVasuthevan/
    - https://www.linkedin.com/in/ramvasuthevan/
    - https://github.com/RamVasuthevan/

# Build settings
theme: minima

header_pages:
  - bitsbipsbricks.markdown
  - thinking-about.markdown
  - quake-articles.markdown
  - tools.markdown
  - projects-I-am-working-on.markdown
  - all-pages.html

sass:
  quiet_deps: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
