name: Jekyll Build Errors and Warnings

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: website/vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('website/Gemfile.lock') }}
      
      - name: Get Ruby version from Gemfile
        run: echo "RUBY_VERSION=$(grep -oP "(?<=ruby \").*(?=\")" website/Gemfile)" >> $GITHUB_ENV

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: './website'

      - name: Get dependencies if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd website
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: Build site and check for warnings or errors
        run: |
          cd website
          bundle exec jekyll build 2>&1 | tee build.log
          ! grep -E 'warning|error' build.log
