name: Jekyll Build Errors and Warnings
on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Build site and check for warnings or errors
      run: |
        bundle exec jekyll build 2>&1 | tee build.log
        ! grep -E 'warning|error' build.log
