name: Jekyll Build Errors and Warnings

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: website/vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('website/Gemfile.lock') }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
      - name: Get dependencies if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd website
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: Build site and check for warnings or errors
        run: |
          cd website
          bundle exec jekyll build 2>&1 | tee build.log
          ! grep -E 'warning|error' build.log
