name: Add Too good to go invoice

on:
  repository_dispatch:
    types: [new-invoice]

jobs:
  process_invoice:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Parse invoice and update repo
      run: |
        # Assign invoice content from payload to EMAIL_CONTENT using here string
        read -r -d '' EMAIL_CONTENT << 'EOF'
        ${{ github.event.client_payload.email_content }}
        EOF
        #EMAIL_ATTACHMENT="${{ github.event.client_payload.email_attachment }}"
        
        # Extract Order ID from the invoice content
        #ORDER_ID=$(echo "$EMAIL_CONTENT" | grep -oP 'order ID \K\w+')
        #echo "Extracted Order ID: $ORDER_ID"
        #echo "$EMAIL_ATTACHMENT"
        
        # This is where you would add the logic to use the extracted order ID
        # and make updates to your repo or any other actions required.
