name: Add Too good to go invoice

on:
  repository_dispatch:
    types: [new-invoice]

jobs:
  process_invoice:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Parse invoice and update repo
      run: |
        # Extract invoice content from payload
        INVOICE_CONTENT="${{ github.event.client_payload.email_content }}"
        
        # Extract Order ID from the invoice content
        ORDER_ID=$(echo "$INVOICE_CONTENT" | grep -oP 'order ID \K\w+')
        echo "Extracted Order ID: $ORDER_ID"
        
        # This is where you would add the logic to use the extracted order ID
        # and make updates to your repo or any other actions required.
