on:
  [push]
jobs:
  yellow-lab-tools-check:
    name: Detect performance and front-end issues
    runs-on: ubuntu-latest
    environment: The Only Environment
    steps:
    - uses: actions/checkout@v2
    - name: Wait for CF Pages
      id: cf-pages
      uses: WalshyDev/cf-pages-await@v1.3.0
      permissions:
        contents: read
        deployments: write
      with:
        apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN  }}
        accountId: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
        project: 'personal-website'
        # Add this if you want GitHub Deployments (see below)
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        commitHash: ${{ steps.push-changes.outputs.commit-hash }}
      - uses: actions/checkout@v2
        with:
          repository: marcuslindblom/yellow-lab-tools
      - uses: marcuslindblom/yellow-lab-tools@v1.2.1
        with:
          url: ${{github.ref_name}}.${{secrets.CLOUDFLARE_PAGES_ROOT_URL}}
          score: 100