on:
  [push]
jobs:
  yellow-lab-tools-check:
    name: Run Yellow Lab Tools
    runs-on: ubuntu-latest
    environment: The Only Environment
    steps:
    - uses: actions/checkout@v2
    - name: Wait for Cloudflare Pages to Deploy
      id: cf-pages
      uses: RamVasuthevan/cf-pages-await@remove-calls-to-updateDeployment
      with:
        apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN  }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        project: 'personal-website'
        commitHash: ${{ steps.push-changes.outputs.commit-hash }}
    - uses: actions/checkout@v2
      with:
        repository: marcuslindblom/yellow-lab-tools
    - uses: marcuslindblom/yellow-lab-tools@v1.2.1
      with:
        url: ${{ github.ref_name }}.${{ secrets.CLOUDFLARE_PAGES_ROOT_URL }}
        score: 100