on:
  [push]
jobs:
  yellow-lab-tools-check:
    name: Detect performance and front-end issues
    runs-on: ubuntu-latest
    steps:
      - name: Test Echo
        run: echo ${{github.ref_name}}
      - uses: actions/checkout@v2
        with:
          repository: marcuslindblom/yellow-lab-tools
      - uses: marcuslindblom/yellow-lab-tools@v1.2.1
        with:
          url: https://ramvasuthevan.ca